import type { Metadata } from "next";
import "@pThunder/app/globals.css";
import BottomTabs from "./BottomTabs";
import FCMClient from "./fcmComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div id="main-contents" className="flex flex-col-reverse w-full h-dvh">
      <FCMClient />
      <div className="relative flex-grow overflow-y-auto overflow-x-hidden">
            {children}
      </div>
    </div>
  );
}
