import type { Metadata } from "next";
import "@pThunder/app/globals.css";
import SideMenu from "./sidemenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div id="main-contents" className="flex flex-row">
      <SideMenu />
      <div className="flex-grow">
        {children}
      </div>
    </div>
  );
}
