import type { Metadata } from "next";
import "@pThunder/app/globals.css";
import PostList from "./PostList";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({
    children, params
}: Readonly<{
    children: React.ReactNode
    params: { boardID: number }
}>) {
    
    return (
        <div className="flex flex-row h-screen items-center justify-center gap-4 mx-24">
            <div className="border rounded-lg w-auto min-w-72 h-3/4 overflow-y-scroll">
                <PostList params={params} />
            </div>
            <div className="border h-3/4 rounded-md flex-grow">
                {children}
            </div>
        </div>
    );
}